---
title: "Credit Risk Dashboard"
output: 
  flexdashboard::flex_dashboard:
      theme: cosmo
      orientation: rows
      vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}

# Resources
#   FlexDashboard: https://rmarkdown.rstudio.com/flexdashboard/using.html

# Libraries
library(shiny)
library(flexdashboard)
library(DT)
library(billboarder)
library(tidyverse)
library(lime)
library(h2o)
library(glue)

# Data
predictions_tbl <- readRDS("00_data/predictions_tbl.rds")
train_tbl <- readRDS("00_data/train_tbl.rds")
test_tbl <- readRDS("00_data/test_tbl.rds")

# H2O Model
h2o.init()
h2o_model <- h2o.loadModel("../02_workshop_h2o_day_1/03_machine_learning/models/StackedEnsemble_AllModels_0_AutoML_20180904_113915")


```

```{css}
.navbar {
    background-color:#2c3e50;
}
```


Risk Scorecard
===================================

Sidebar {.sidebar}
-----------------------------------

#### Applicant ID

```{r}
# Selection
applicant_ids <- unique(predictions_tbl$SK_ID_CURR) %>% as.character()

selectInput("applicant_id", 
            label = NULL, 
            applicant_ids)
```

***

#### H2O Default Prediction

```{r}
h3(textOutput("default_prediction"), class="text-center")
```


```{r}
output$default_prediction <- renderText({
    req(input$applicant_id)
    
    selected_applicant_id <- predictions_tbl$SK_ID_CURR[[1]]
    selected_applicant_id <- input$applicant_id
    
    applicant_tbl <- predictions_tbl %>%
        filter(SK_ID_CURR == selected_applicant_id)
    
    default_prediction <- applicant_tbl$predict
    
    ifelse(default_prediction == 1, "Yes", "No")
})
```

***

#### H2O Probability Of Default

```{r}
gaugeOutput("default_risk", width = "220px", height = "130px")
```

```{r, context="server"}
output$default_risk <- renderGauge({
    
    req(input$applicant_id)
    
    selected_applicant_id <- predictions_tbl$SK_ID_CURR[[1]]
    selected_applicant_id <- input$applicant_id
    
    applicant_tbl <- predictions_tbl %>%
        filter(SK_ID_CURR == selected_applicant_id)
    
    prob_of_default <- applicant_tbl$p1
    
    gauge(
        value = round(prob_of_default * 100, digits = 1),
        min = 0,
        max = 100,
        gaugeSectors(
            success = c(0, 33),
            warning = c(33, 66),
            danger  = c(66, 100),
            colors = c("#18BC9C", "#CCBE93", "#e31a1c")
        ),
        symbol = "%"
    )
})
```

***

This application enables a manager to quickly evaluate a loan applicant to determine risk of default and contributing factors. This app is powered by [H2O](https://www.h2o.ai/) and [LIME](https://github.com/thomasp85/lime).

***

[Business Science](http://www.business-science.io/) Custom Machine Learning Workshop for:



```{r}
strong("S&P Global Market Intelligence") %>%
    a(href = "https://www.spglobal.com/marketintelligence/en/") %>%
    p(class = "text-center")
```



Row 1: External Credit Reporting Agencies
-----------------------------------


```{css}
.value-box .value-output,
.value-box .caption {
    font-size: 24px;
}
```

### Ext Source 1

```{r}
valueBoxOutput("ext_source_1")
```


```{r, context="server"}
output$ext_source_1 <- renderValueBox({
    
    req(input$applicant_id)
    
    selected_applicant_id <- predictions_tbl$SK_ID_CURR[[1]]
    selected_applicant_id <- input$applicant_id
    
    ext_source_median <- median(predictions_tbl$EXT_SOURCE_1)
    
    applicant_tbl <- predictions_tbl %>%
        filter(SK_ID_CURR == selected_applicant_id)
    
    ext_source_value <- applicant_tbl$EXT_SOURCE_1
    
    ext_source_caption <- glue(
        "{round(ext_source_value, 2)} (Median: {round(ext_source_median, 2)})"
    )
    
    valueBox(
        "Ext Source 1",
        caption = ext_source_caption,
        color = "#2c3e50"
    )
    
})
```


### Ext Source 2

```{r}
valueBoxOutput("ext_source_2")
```


```{r, context="server"}
output$ext_source_2 <- renderValueBox({
    
    req(input$applicant_id)
    
    selected_applicant_id <- predictions_tbl$SK_ID_CURR[[1]]
    selected_applicant_id <- input$applicant_id
    
    ext_source_median <- median(predictions_tbl$EXT_SOURCE_2)
    
    applicant_tbl <- predictions_tbl %>%
        filter(SK_ID_CURR == selected_applicant_id)
    
    ext_source_value <- applicant_tbl$EXT_SOURCE_2
    
    ext_source_caption <- glue(
        "{round(ext_source_value, 2)} (Median: {round(ext_source_median, 2)})"
    )
    
    valueBox(
        "Ext Source 2",
        caption = ext_source_caption,
        color = "#e31a1c"
    )
    
})
```

### Ext Source 3

```{r}
valueBoxOutput("ext_source_3")
```


```{r, context="server"}
output$ext_source_3 <- renderValueBox({
    
    req(input$applicant_id)
    
    selected_applicant_id <- predictions_tbl$SK_ID_CURR[[1]]
    selected_applicant_id <- input$applicant_id
    
    ext_source_median <- median(predictions_tbl$EXT_SOURCE_3)
    
    applicant_tbl <- predictions_tbl %>%
        filter(SK_ID_CURR == selected_applicant_id)
    
    ext_source_value <- applicant_tbl$EXT_SOURCE_3
    
    ext_source_caption <- glue(
        "{round(ext_source_value, 2)} (Median: {round(ext_source_median, 2)})"
    )
    
    valueBox(
        "Ext Source 3",
        caption = ext_source_caption,
        color = "#18BC9C"
    )
    
})
```

Row 2: Applicant Analysis 
-----------------------------------

```{r}
lime_input <- reactive({
    
    req(input$applicant_id)
    
    selected_applicant_id <- predictions_tbl$SK_ID_CURR[[1]]
    selected_applicant_id <- input$applicant_id
    
    # LIME
    explainer <- train_tbl %>%
        select(-TARGET) %>%
        lime(
            model           = h2o_model,
            bin_continuous  = TRUE,
            n_bins          = 4,
            quantile_bins   = TRUE
        )
    
    explanation <- test_tbl %>%
        filter(SK_ID_CURR == selected_applicant_id) %>%
        select(-TARGET) %>%
        lime::explain(
            explainer = explainer,
            n_labels   = 1,
            n_features = 8,
            n_permutations = 5000,
            kernel_width   = 1,
            feature_select = "forward_selection"
        )
    
    explanation
})
```

### LIME Metrics {data-width=33}

```{r}
dataTableOutput("lime_metrics")
```

```{r}
output$lime_metrics <- renderDataTable({
    
    label      <- unique(lime_input()$label)[[1]]
    label_prob <- unique(lime_input()$label_prob)[[1]]
    model_r2   <- unique(lime_input()$model_r2)[[1]]

    lime_metrics_tbl <- tibble(
        `Class Prediction`  = toupper(label),
        `Class Probability` = round(label_prob, 2),
        `Model R2`          = round(model_r2, 2)
    ) %>%
        gather(key = "Metric", value = "Value")
    
    DT::datatable(
        lime_metrics_tbl,
        rownames = NULL,
        options = list(
            dom = 't', 
            bSort = FALSE, 
            paging = FALSE
        )
    )
})
```

### LIME Model Interpretation Plot {data-width=67}

```{r}
billboarderOutput('lime_explanation')
```

```{r, context="server"}
output$lime_explanation <- renderBillboarder({
    
    explanation_transformed_tbl <- lime_input() %>%
        as.tibble() %>%
        select(feature:feature_desc) %>%
        mutate(direction = ifelse(feature_weight > 0, "Supports", "Contradicts")) %>%
        mutate(direction = factor(direction, levels = c("Supports", "Contradicts"))) %>%
        mutate(feature_desc = as_factor(feature_desc) %>%
                   fct_reorder(abs(feature_weight))) %>%
        arrange(desc(feature_desc))
    
    billboarder(data = explanation_transformed_tbl) %>%
        bb_aes(x = feature_desc, y = feature_weight, group = direction) %>%
        bb_barchart(rotated = TRUE, stacked = TRUE) %>%
        bb_y_grid(show = TRUE) %>%
        bb_colors_manual(
            Supports    = "#2c3e50",
            Contradicts = "#e31a1c"
        ) %>%
        bb_tooltip(format = list(
            value = htmlwidgets::JS("function(x) {return parseFloat(x).toFixed(3)}")
        )) 
    
})
```

